version: "3"
services:
  rs-dev:
    container_name: "rs-dev"
    build: .
    ports:
      - "3000:3000"
      - "10214:10214"
    volumes:
      - .:/workdir
    networks:
      - default
  
# Define network default as external docker network bso_staging_default
networks:
  default:
    name: ${DOCKER_NETWORK}